### PR TITLE
[WIP] Refactor scripts for part 3

### PR DESCRIPTION
**Pull request by jakepruitt**
@Perryo - I started refactoring the quanitization script, which will fix the quantization errors you were seeing. It will also be the pattern I will be using for other scripts. I'm moving slowly, and not done yet, but I'm seeing good performance improvements already.

cc/ @GCrispino @ApertureTS @SreeniASU

### CODE REVIEW

**Comment by Perryo** [comment]
@jakepruitt 
Looks good, I'm going to merge this. Finished up this section of the report as well, I need to add information on what you have done, so if you want to check that it is accurate after that would rock. 
Thanks for taking a look at this!

**Comment by jakepruitt** [comment]
NOOOOOOOOOO It said WIP as in "Work in Progress", as in not ready to merge. I'll use "DO NOT MERGE" from now on.

**Comment by Perryo** [comment]
Whoops, I thought you opened the request to merge it. I can always revert it

**Comment by jakepruitt** [comment]
Nope, you can leave it in master, I'll create a new PR that fixes things. I tend to create work in progress pull requests so everyone can see what I am working on and provide feedback while I'm working on it. It makes things more open, and allows the team to catch errors early on, and not after I've spent a week working on something. Fine for now, but in the future, just give a :+1: indicating you're fine with it and I'll let you know when I'm ready to merge it.

**Comment by Perryo** [comment]
Since its a WIP, can we add the blockshaped function and coordinate calculation back? I already went through the trouble of explaining and diagramming them out in the report. Any performance impacts were not really related to these but rather the size and number of frames of the video which the professor already clarified wont be an issue.

**Pull request merged**
