### PR TITLE
Refactor quantized compare method

### PR DESCRIPTION
**Pull request by jakepruitt**
Rather than quantizing the target frame at the time of the request, use the quantized data from the histogram dictionary.

### CODE REVIEW

**Comment by jakepruitt** [comment]
@Perryo seeing a little bit better results here. @Perryo could you try this out and compare it to the master results and see what is better on your machine?

**Comment by jakepruitt** [comment]
@Perryo Found an error when running:

```
python match_frame.py 100 5 5 ../test/project1/R2.mp4
```

One of the indexes returned in this process was `264` even though there were only 263 frames. I think this has to do with the way the frames were indexed - probably starting with 1 instead of 0. I fixed it by subtracting 1 from the index.

**Comment by Perryo** [comment]
@jakepruitt 
Are you available? Can we take a look at the issues you are seeing? This is all working from my end.

**Comment by jakepruitt** [comment]
Hey, @Perryo, I'm available now if you want to chat about it.

Hangout:
https://hangouts.google.com/call/ssqbwotpgkbaz23iwgkjc4sonma

**Comment by jakepruitt** [comment]
Per chat - we're removing the `replace_value` function, which produces the same results when the histogram is calculated without it. We're also comparing apples to apples with the target frame from the frame histogram dictionary.

**Pull request merged**
