### PR TITLE
Added full test suite and converted to video

### PR DESCRIPTION
**Pull request by jakepruitt**
In order to make development of Part 1 of project 2 a little more stable, I added a test script that will compare the output of the program to expected outputs. If any unintentional changes are made to Part 1, we will be able to tell immediately.

I also was able to create a video of the Y values in the 10x10 region selected in the original movie. I will be using this as a test fixture to compare the reverse-encoding operations done in part 5.

Also refactored a few things and added some documentation

cc/ @GCrispino @ApertureTS @SreeniASU @Perryo

### CODE REVIEW

**Comment by jakepruitt** [comment]
Also incorporates @ApertureTS initial commit for part 5

**Comment by jakepruitt** [comment]
Got options 1-3 turned back into playable videos, but part 4 is exhibiting some artifacts when decoding into the video - many white pixels are randomly becoming black. I do not know if this is an error on the decoding side or the encoding side, but would appreciate having @ApertureTS look at it if you have time.

**Comment by ApertureTS** [comment]
@jakepruitt I plan on getting up around 9 am sunday, let me know if you are available before 11am. I won't be available much after that. I didn't find what is causing the errors

**Comment by jakepruitt** [comment]
@ApertureTS going to dive into right now. Seems like values are being calculated with negative pixel values. Will spend some time hunting now.

**Comment by jakepruitt** [comment]
@ApertureTS Figured it out. Turns out due to floating-point arithmetic ( :question: ) the comparisons of:

```
alpha2 < 0 or alpha2 > 1
```

Would return true if alpha2 equaled 0 or 1. This ~~terrible~~ interesting bug was fixed and everything looks good for encoding videos from tpc files. If you could do some code review I'd appreciate it.

**Pull request merged**
